SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UB
JOIN USED_GOODS_USER AS UU ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS LIKE "DONE"
GROUP BY WRITER_ID
HAVING SUM(PRICE) >=700000
ORDER BY TOTAL_SALES;