SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE LIKE "2022-01%"
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;