SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
 ,ROUND(AVG(RW.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
    JOIN REST_REVIEW AS RW
    ON RI.REST_ID = RW.REST_ID
group by RI.REST_ID
HAVING RI.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC;